name: Core
version: '1.0-SNAPSHOT'
main: me.tomqnto.core.Core
api-version: '1.21'
authors: [ Tomqnto ]

commands:
  "setrank":
    usage: "/<command> <player>"
    description: "Sets a player's rank"
    aliases: ["sr"]
  "removerank":
    usage: "/<command> <player>"
    description: "Removes a player's rank"
    aliases: ["rr", "delrank", "dr"]
