name: Core
version: '1.0-SNAPSHOT'
main: me.tomqnto.core.Core
api-version: '1.21'
authors: [ Tomqnto ]
depend: [ProtocolLib]

commands:

  setrank:
    usage: /<command> <player>
    description: Sets a player's rank
    aliases: [sr]

  removerank:
    usage: /<command> <player>
    description: Removes a player's rank
    aliases: [rr, dr, delrank]

  register:
    usage: /<command> <password> <confirmpassword>
    description: Registers the player

  unregister:
    usage: /<command> <player>
    description: Unregisters the player

  login:
    usage: /<command> <password>
    description: Let players log-in to the server

  setstate:
    usage: /<command> <state>
    description: Changes the server state

permissions:
  core.rank.*:
    description: Allows players to use rank commands
    default: false
    children:
      - core.rank.setrank: true
      - core.rank.removerank: true

  core.rank.setrank:
    description: Allows players to set another player's rank
    default: false

  core.rank.removerank:
    description: Allows players to remove another player's rank
    default: false

  core.rank.default:
    description: Allows players to use default commands
    default: true
    children:
      -

  core.rank.helper:
    description: Allows players to use helper commands
    default: false
    children:
      - core.rank.default: true

  core.rank.mod:
    description: Allows players to use mod commands
    default: false
    children:
      - core.rank.helper: true

  core.rank.admin:
    description: ALlows players to use admin commands
    default: false
    children:
      - core.rank.mod: true
      - core.rank.*: true

  core.rank.owner:
    description: Allows players to use owner commands
    default: false
    children:
      - core.rank.*: true