name: Core
version: '1.0-SNAPSHOT'
main: me.tomqnto.core.Core
api-version: '1.21'
authors: [ Tomqnto ]
softdepend: [ProtocolLib]

commands:

  setrank:
    usage: /<command> <player>
    description: Sets a player's rank
    aliases: [sr]

  resetrank:
    usage: /<command> <player>
    description: Removes a player's rank
    aliases: [rr]

  register:
    usage: /<command> <password> <confirmpassword>
    description: Registers the player

  unregister:
    usage: /<command> <player>
    description: Unregisters the player

  login:
    usage: /<command> <password>
    description: Let players log-in to the server

  setstate:
    usage: /<command> <state>
    description: Changes the server state

permissions:

  core.auth.command.register:
    description: Allows players to use the register command
    default: false

  core.auth.command.login:
    description: Allows players to use the login command
    default: false

  core.rank.command.*:
    description: Allows players to use rank commands
    default: false
    children:
      - core.rank.command.setrank
      - core.rank.command.removerank

  core.rank.command.setrank:
    description: Allows players to set another player's rank
    default: false

  core.rank.command.removerank:
    description: Allows players to remove another player's rank
    default: false

  core.group.default:
    description: Allows players to use default commands
    default: true
    children:
      - core.auth.command.register
      - core.auth.command.login

  core.group.youtube:
    description: Allows players to use youtuber commands
    default: false
    children:
      - core.group.default

  core.group.helper:
    description: Allows players to use helper commands
    default: false
    children:
      - core.group.default

  core.group.mod:
    description: Allows players to use mod commands
    default: false
    children:
      - core.group.helper

  core.group.admin:
    description: ALlows players to use admin commands
    default: false
    children:
      - core.group.mod
      - core.rank.command.*

  core.group.owner:
    description: Allows players to use owner commands
    default: false
    children:
      - core.*