name: Core
version: '1.0-SNAPSHOT'
main: me.tomqnto.core.Core
api-version: '1.21'
authors: [ Tomqnto ]

commands:
  setrank:
    usage: /<command> <player>
    description: Sets a player's rank
    aliases: [sr]
  removerank:
    usage: /<command> <player>
    description: Removes a player's rank
    aliases: [rr, dr, delrank]


permissions:
  core.rank.*:
    description: Allows players to use rank commands
    default: false
    children:
      - core.rank.setrank
      - core.rank.removerank

  core.rank.setrank:
    description: Allows players to set another player's rank
    default: false

  core.rank.removerank:
    description: Allows players to remove another player's rank
    default: false

  core.rank.default:
    description: Allows players to use default commands
    default: true
    children:
      -

  core.rank.helper:
    description: Allows players to use helper commands
    default: false
    children:
      - core.rank.default

  core.rank.mod:
    description: Allows players to use mod commands
    default: false
    children:
      - core.rank.helper

  core.rank.admin:
    description: ALlows players to use admin commands
    default: false
    children:
      - core.rank.mod
      - core.rank.*

  core.rank.owner:
    description: Allows players to use owner commands
    default: false
    children:
      - core.rank.admin